spring.application.name=kitchen-service
server.port=8082

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=kitchen-service-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.enable.idempotence=true

app.topics.order-placed=order-placed
app.topics.order-ready=order-ready

management.endpoints.web.exposure.include=health,info
