spring.application.name=enduser-service
server.port=8084

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=enduser-service-group

app.topics.order-out-for-delivery=order-out-for-delivery

management.endpoints.web.exposure.include=health,info
